[package]
name = "aoc-2018"
version = "0.1.0"
authors = ["Jeremy Banks <_@jeremy.ca>"]
edition = "2018"

[dependencies]
itertools = "0.7.11"
derive_more = "0.13.0"
regex = "1.1.0"
typed-arena = "1.4.1"
