#!/bin/bash
set -euo pipefail;
cargo +nightly fmt;
cargo +nightly fix --allow-dirty --allow-staged;
cargo +nightly clippy;
rm -rf results.txt;
clear;
cargo +nightly build;
clear;
(target/debug/aoc-2018 "$@" && 
cargo +nightly build --release && clear && target/release/aoc-2018 "$@" | tee results.txt) || (
    s=$?;
    clear;
    echo "$(tput setaf 1)Program exited with status $s. Trying again for debugging...$(tput sgr0)";
    set -x;
    cargo +nightly build;
    RUST_BACKTRACE=1 target/debug/aoc-2018 "$@";
);
