force_explicit_abi = false
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
newline_style = "Unix"
overflow_delimited_expr = true
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
